package paths;

public enum AlgorithmMode {
    DIJKSTRA, BI_DIJKSTRA, BI_DIJKSTRA_SAME_DIST, A_STAR, A_STAR_LANDMARKS, BI_A_STAR_SYMMETRIC, BI_A_STAR_CONSISTENT, BI_A_STAR_LANDMARKS, REACH, BI_REACH, CONTRACTION_HIERARCHIES, SINGLE_TO_ALL, BOUNDED_SINGLE_TO_ALL, REACH_A_STAR, REACH_LANDMARKS, BI_REACH_A_STAR;
}
