package paths;

public enum AlgorithmMode {
    DIJKSTRA, BI_DIJKSTRA, TWO_PHASE_DIJKSTRA, A_STAR, BI_A_STAR_SYMMETRIC, BI_A_STAR_CONSISTENT, BI_A_STAR_LANDMARKS, SUPER_ULTRA_FAST, A_STAR_LANDMARKS;
}
