package paths;

public enum AlgorithmMode {
    DIJKSTRA,
    DUPLICATE_DIJKSTRA,
    BI_DIJKSTRA,
    BI_DIJKSTRA_SAME_DIST,
    BI_DIJKSTRA_DENSITY,
    A_STAR,
    A_STAR_LANDMARKS,
    BI_A_STAR_SYMMETRIC,
    BI_A_STAR_CONSISTENT,
    BI_A_STAR_LANDMARKS,
    REACH,
    REACH_A_STAR,
    REACH_LANDMARKS,
    BI_REACH,
    BI_REACH_A_STAR,
    BI_REACH_LANDMARKS,
    CONTRACTION_HIERARCHIES,
    SINGLE_TO_ALL,
    BOUNDED_SINGLE_TO_ALL,
    CONTRACTION_HIERARCHIES_LANDMARKS
}
